version: '3.8'

services:
  mssql:
    container_name: sqlserver-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Chirripo3820
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data:
    driver: local
